import { Link } from 'react-router-dom'
import { Helmet } from 'react-helmet-async'
import { ArrowLeft, Zap } from 'lucide-react'
import PublicFooter from '@/components/layout/PublicFooter'

const LAST_UPDATED = 'March 21, 2026'

const sections = [
  {
    title: '1. Acceptance of Terms',
    body: `By creating an account or using Wrively, you agree to these Terms of Service. If you do not agree, do not use the service. We may update these terms from time to time and will notify you of material changes by email or in-app notice.`,
  },
  {
    title: '2. Description of Service',
    body: `Wrively is an AI-powered content tool that helps founders and professionals create LinkedIn posts, comment suggestions, and draft rewrites. The service is provided "as is" and is intended for personal and professional use only.`,
  },
  {
    title: '3. Eligibility',
    body: `You must be at least 18 years old to use Wrively. By using the service, you confirm that you meet this requirement and that the information you provide during registration is accurate.`,
  },
  {
    title: '4. Your Account',
    body: `You are responsible for keeping your account credentials secure. You agree not to share your account with others or use it for any purpose that violates these terms. We reserve the right to suspend or terminate accounts that violate our policies.`,
  },
  {
    title: '5. Acceptable Use',
    body: `You agree not to use Wrively to generate content that is misleading, defamatory, harassing, or in violation of any applicable law. You are solely responsible for the content you publish using output generated by Wrively. We do not endorse or take responsibility for content posted on third-party platforms.`,
  },
  {
    title: '6. AI-Generated Content',
    body: `Content generated by Wrively is produced using large language models. We do not guarantee that generated content is accurate, complete, or suitable for any particular purpose. You should review all AI-generated content before publishing. Wrively is not liable for any consequences arising from the use of generated content.`,
  },
  {
    title: '7. Intellectual Property',
    body: `You retain ownership of the content you input into Wrively. Output generated on your behalf is yours to use. Wrively retains all rights to its platform, brand, and underlying technology. You may not copy, resell, or reverse-engineer any part of the service.`,
  },
  {
    title: '8. Subscription and Billing',
    body: `Wrively offers free and paid plans. Paid plans are billed monthly and can be cancelled at any time. Cancelling stops future charges but does not trigger a refund for the current billing period. We reserve the right to change pricing with 30 days notice.`,
  },
  {
    title: '9. Privacy',
    body: `Your use of Wrively is also governed by our Privacy Policy. By using the service, you consent to the collection and use of information as described therein. We do not sell your personal data to third parties.`,
  },
  {
    title: '10. Limitation of Liability',
    body: `To the fullest extent permitted by law, Wrively and its team will not be liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability to you for any claim will not exceed the amount you paid us in the 12 months preceding the claim.`,
  },
  {
    title: '11. Termination',
    body: `You may delete your account at any time from Settings. We may suspend or terminate your account if you violate these terms. Upon termination, your data will be deleted in accordance with our data retention policy.`,
  },
  {
    title: '12. Contact',
    body: `If you have questions about these terms, contact us at hello@wrively.com.`,
  },
]

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <Helmet>
        <title>Terms of Service | Wrively</title>
        <meta name="description" content="Read the Wrively Terms of Service. Learn about usage, content ownership, subscriptions, and your rights when using the Wrively Voice Layer platform." />
        <link rel="canonical" href="https://wrively.com/terms" />
        <meta property="og:title" content="Terms of Service | Wrively" />
        <meta property="og:url" content="https://wrively.com/terms" />
        <meta name="robots" content="noindex, follow" />
      </Helmet>
      {/* Header */}
      <header className="sticky top-0 z-10 bg-background/95 backdrop-blur-sm border-b border-border">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-7 h-7 bg-primary-gradient rounded-lg flex items-center justify-center">
              <Zap className="w-4 h-4 text-white" />
            </div>
            <span className="font-bold text-text text-base">Wrively</span>
          </Link>
          <Link
            to="/"
            className="inline-flex items-center gap-1.5 text-sm text-text-muted hover:text-text transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Back
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-10 md:py-14">
        {/* Title block */}
        <div className="mb-10">
          <h1 className="text-2xl font-bold text-text mb-2">Terms of Service</h1>
          <p className="text-sm text-text-muted">Last updated: {LAST_UPDATED}</p>
        </div>

        {/* Intro */}
        <div className="bg-surface border border-border rounded-card px-5 py-4 mb-8">
          <p className="text-sm text-text-muted leading-relaxed">
            These terms govern your use of Wrively. Please read them carefully.
            By using Wrively you agree to be bound by these terms. If you have
            questions, email us at{' '}
            <a href="mailto:hello@wrively.com" className="text-primary hover:text-primary-hover transition-colors">
              hello@wrively.com
            </a>
            .
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {sections.map(s => (
            <section key={s.title}>
              <h2 className="text-base font-semibold text-text mb-2">{s.title}</h2>
              <p className="text-sm text-text-muted leading-relaxed">{s.body}</p>
            </section>
          ))}
        </div>

      </main>
      <PublicFooter />
    </div>
  )
}
